export const data = {
    code: 0,
    result: {
        standardAdList: [],
        liteAdList: [
            {
                _id: "6386b97eb54b10001dec4fe3",
                gymName: "부평 mgym",
                gymPhotoBig:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/184c64497a13d462cd/NQabER8mYacC1vgShPrpLDJKrgyTQCVVj1.Big_241226_부평_mgym_19.jpg",
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/184c64497a13d462cd/NQabER8mYacC1vgShPrpLDJKrgyTQCVVj1.Big_241226_부평_mgym_19.jpg",
                address: "인천 부평구 부평동",
                location: [126.7296525161124, 37.49880655738467],
                review: {
                    rate: 5,
                    count: 3,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "3258eb8f-f052-49fe-a2f2-c998a86030fe",
                    productId: "90143067-704f-46c3-a81b-1b3f126d7ff1",
                    productName: "헬스 회원권",
                    defaultPrice: 396000,
                    dagymPrice: 396000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "️주차 4시간",
                },
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: true,
                isDagymRecommended: true,
            },
            {
                _id: "6881e1b50f28c6789baaac24",
                gymName: "부평 레디짐",
                gymPhotoBig:
                    "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/e02957ce-be1a-4d69-ab4f-229fb88f9d08/1758528424177_7d670d46-499f-4ba5-b4fc-d156df99a9eb.jpg",
                gymPhotoSmall:
                    "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/e02957ce-be1a-4d69-ab4f-229fb88f9d08/1758528424177_7d670d46-499f-4ba5-b4fc-d156df99a9eb.jpg",
                address: "인천 부평구 산곡동",
                location: [126.7146091, 37.5033211],
                review: {
                    rate: 5,
                    count: 2,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "2282e3cf-a307-4e32-b959-95f139c48a30",
                    productId: "0e48a27f-39b8-4274-b835-ef79762df5b5",
                    productName: "헬스 회원권",
                    defaultPrice: 396000,
                    dagymPrice: 396000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 10,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스"],
                program: {
                    free: "ot1회",
                },
                service: {
                    free: "주차 무제한",
                },
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: true,
                isDagymRecommended: true,
            },
        ],
        centerList: [
            {
                _id: "5a73c5aa6959a655ea649cdb",
                gymName: "부평 더블유짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/161543c22ff45b4645/4K6uVdbJnWndJAmYHdfhiJGFKMyGznaShXc7ckxGwPmZ.jpg",
                address: "인천 부평구 부평동",
                location: [126.722819, 37.492248],
                review: {
                    rate: 4.57,
                    count: 26,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "ba2dcfc8-e48c-4b46-96c8-69f3734a1f8c",
                    productId: "2e07e226-3e74-42e9-901a-8131530893ed",
                    productName: "헬스 회원권",
                    defaultPrice: 360000,
                    dagymPrice: 342000,
                    dagymPriceRemainingCount: 5,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "스피닝", "그룹P.T"],
                program: {
                    free: "O.T (3개월 등록시 1회 / 6개월 등록시 2회)",
                },
                service: {
                    free: "주차 (2시간 - SUV/외제차는 제외)",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "654c5a795b1869001db38133",
                gymName: "부평 스페시맨GYM",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18bb2416b9a4aa6cfe/2YCYcqM1JvMNWtKHZmACpYjqRwnPfNStyjje.Big_231121_부평_스페시멘GYM_11.jpg",
                address: "인천 부평구 부평동",
                location: [126.7236466023847, 37.49293162907103],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "1839c011-1cd5-4e08-846b-eff14b5872af",
                    productId: "34e64277-54b5-4339-9de9-84d7211b1e70",
                    productName: "1:1 PT ",
                    defaultPrice: 650000,
                    dagymPrice: 650000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "count",
                    periodUnit: "month",
                    period: 2,
                    count: 10,
                },
                exhibitionRemainingCount: null,
                tags: ["P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "️운동복 / ️개인락카 / ️수건 / ️주차 (부평 문화의거리 공영주차장 주차 1시간 무료지원)",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "68cbf457a4314ecbf7fd9be2",
                gymName: "부평 3세트짐&라인업PT",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/69f34b7e-8063-44d5-8e52-91c30c2d54d6/1758196730380_37866c66-7274-42a1-9088-d5a14ed14036.jfif",
                address: "인천 부평구 부평동",
                location: [126.7250109, 37.4909368],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "05416eef-2010-4b4b-bcde-8a66f65c7bfd",
                    productId: "10461545-4033-490b-b087-b375c215178b",
                    productName: "물리치료사 교정pt&필라테스 (10회)",
                    defaultPrice: 550000,
                    dagymPrice: 550000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "count",
                    periodUnit: "month",
                    period: 1,
                    count: 10,
                },
                exhibitionRemainingCount: null,
                tags: [],
                program: {
                    free: "AI 체형분석 +움직임평가",
                },
                service: {
                    free: "무료주차2시간 / 운동복 / 개인라카 / 헬스권",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: 0.5,
                isSportsFacilityCertified: true,
                isDagymRecommended: false,
            },
            {
                _id: "61936a38e271c900398564e1",
                gymName: "부평 PT의정석 운동재활센터",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17d27d6ecb9117de10/4K7y1LZk6uGHeY8uKFvvoerx8vAzcMhZhj9HHeW8fBgs.jpg",
                address: "인천 부평구 부평동",
                location: [126.7239422822052, 37.49672824822733],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "a2f18c0a-f5fe-4c7d-af3b-582b6fa813e6",
                    productId: "94fca1f0-056a-45cc-96a0-9d88578bc248",
                    productName: "1:1 P.T (횟수제) ",
                    defaultPrice: 690000,
                    dagymPrice: 690000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "count",
                    periodUnit: "month",
                    period: 1,
                    count: 10,
                },
                exhibitionRemainingCount: null,
                tags: ["P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "수건 / 락커 / Wi-fi",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "64d0d308d7c1bd001d65b785",
                gymName: "부평 키워드핏",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/189cfb859c73854ec6/2WP84oMRYWsBGbyDoH6g7P6yXNnRGmBRWo5B.background_photo.jpg",
                address: "인천 부평구 부평동",
                location: [126.7217453, 37.4977424],
                review: {
                    rate: 5,
                    count: 3,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "d02c07f1-5878-4fff-a528-c89a18a2269d",
                    productId: "c6a135b0-7ae6-4622-958a-b712bb9d1ccd",
                    productName: "헬스 회원권",
                    defaultPrice: 420000,
                    dagymPrice: 399000,
                    dagymPriceRemainingCount: null,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "수건 / 락커",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "65ee9ca2b2e9a2001dc1f7e3",
                gymName: "부평남부 바디홀릭 필라테스",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/18e2c13da7355cff1/Mc1imjFsQXR1SQnEbNeLadYVeouuAFsiL5.센터 Big 복사.jpg",
                address: "인천 부평구 부평동",
                location: [126.7246396267085, 37.48733420227458],
                review: {
                    rate: 5,
                    count: 3,
                },
                isWomenOnly: false,
                isReservationRequired: true,
                isLowestPrice: true,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "d7c6b7b7-9d3d-4099-8309-49c910dfbbad",
                    productId: "42613753-44f8-4350-a494-066211651d3f",
                    productName: "6:1 필라테스",
                    defaultPrice: 800000,
                    dagymPrice: 720000,
                    dagymPriceRemainingCount: null,
                    productCategory: "general",
                    productType: "count",
                    periodUnit: "month",
                    period: 12,
                    count: 100,
                },
                exhibitionRemainingCount: null,
                tags: ["필라테스"],
                program: {
                    free: "",
                },
                service: {
                    free: "️수건/ 샤워시설 / 반신욕기 / ️공용락커",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "66974a7301d0e4001dbc7b94",
                gymName: "부평 초심PTX메루치양식장",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/190befad34b36fe7a8/2ZyUVawhgeJu3EGGNJgaBgpyaU2X9qMCR8oA.Big_2.jpg",
                address: "인천 부평구 부평동",
                location: [126.7240476178598, 37.485359619013],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "c8ae6cda-2870-4256-b88e-1487bd4ebbdc",
                    productId: "858a84e4-8c4f-4351-8f14-8ba9544965d5",
                    productName: "1:1PT",
                    defaultPrice: 2250000,
                    dagymPrice: 2250000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "count",
                    periodUnit: "month",
                    period: 5,
                    count: 50,
                },
                exhibitionRemainingCount: null,
                tags: ["P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "️주차 / ️공용락커",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "60c0a19ac70b9e003995a855",
                gymName: "부개 팀타이거복싱짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/179f0774361ef22f2/kXYbCnxsTYFHiFCvUChrcYKP1MrhMobhTw2sqAaWLP.jpg",
                address: "인천 부평구 부개동",
                location: [126.7355105444783, 37.49741872785523],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "d5bf7b4a-538c-42ba-9fba-5d1767d36bb5",
                    productId: "3d26eb3e-fa32-496c-b38a-a7188e7f1e68",
                    productName: "복싱",
                    defaultPrice: 1050000,
                    dagymPrice: 1050000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["복싱"],
                program: {
                    free: "G.X (20시)",
                },
                service: {
                    free: "Wi-fi / 수건 / 락커",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "6183671e6bdf97003910046b",
                gymName: "산곡 플랜A피트니스",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17ce94ad08d5c34447/4K7xr2p8vPEYxHxpJnCkzgQfgoA1CHrTYzpizPBjPa23.jpg",
                address: "인천 부평구 산곡동",
                location: [126.7129941800497, 37.50214891920522],
                review: {
                    rate: 4.92,
                    count: 13,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "275049c5-87b1-4f21-bb8d-6f921829a6cc",
                    productId: "3b6d88df-31d6-49b7-87f3-9c9970a9b25b",
                    productName: "헬스 회원권",
                    defaultPrice: 396000,
                    dagymPrice: 396000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "탁구", "스쿼시"],
                program: {
                    free: "",
                },
                service: {
                    free: "주차 150분 / Wi-fi",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "66c7ef9801d0e4001dd151e9",
                gymName: "부개 용인대 런주짓수&런킥복싱",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1917cffea84371eb27/2YBg2GXAJthTsdHAGWEndNv5X9p7uUAu7kHe.background_photo.jpg",
                address: "인천 부평구 부개동",
                location: [126.7354623734008, 37.49800880688532],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "8c1cbc2a-e06c-4e17-825d-b2854ec329b2",
                    productId: "34a066e2-f39f-44d8-9d28-7510060a03d2",
                    productName: "용인대 런주짓수 & 런킥복싱 회원권",
                    defaultPrice: 1200000,
                    dagymPrice: 1200000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["주짓수", "킥복싱"],
                program: {
                    free: "",
                },
                service: {
                    free: "주차 무료 서비스",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "636b0d23d6679f001d132deb",
                gymName: "부평 PT시작",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1845a2b539e5f19578/4K8ggnJZ5AD7w3khCU7XVtjhLAGinLX5NPdxT2qVqVpT.jpg",
                address: "인천 부평구 부평동",
                location: [126.7210351983935, 37.50489982808945],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: true,
                isLowestPrice: false,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "5968967a-f69b-4402-80aa-b4e07417737a",
                    productId: "99538506-1293-4477-a144-60fa795a2a57",
                    productName: "1:1 PT ",
                    defaultPrice: 2750000,
                    dagymPrice: 2750000,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "count",
                    periodUnit: "month",
                    period: 6,
                    count: 50,
                },
                exhibitionRemainingCount: null,
                tags: ["P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "운동복 / 개인락커 / 커피이용",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "615e6c826bdf9700390c9e95",
                gymName: "부개 골드짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17c58d7dcf52f4d98d/4K7xorRJgwgywmRHpZMi7K7cwoVQDFHobqagY4tZmiBh.jpg",
                address: "인천 부평구 부개동",
                location: [126.738379788626, 37.49366744230181],
                review: {
                    rate: 4,
                    count: 4,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "022fe90a-7e43-4b30-9a06-f949af60e06b",
                    productId: "e44cf1ae-0a69-4129-90aa-81dfb01af919",
                    productName: "헬스 회원권",
                    defaultPrice: 400000,
                    dagymPrice: 360000,
                    dagymPriceRemainingCount: 3,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "680f2c0a16cdca7bb320e4cc",
                gymName: "부평 아름다훈PT",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/2d2f90e7-7006-4e4b-8633-7d05dc6407ac/1745824358582_8aa5dd26-6c8a-4aae-ae79-36cfe21dcab6.jpg",
                address: "인천 부평구 부평동",
                location: [126.7257838, 37.5055506],
                review: {
                    rate: 0,
                    count: 0,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "c5da6a3c-6f3e-47b0-8b35-9eaf86aef550",
                    productId: "f9e121c0-2d31-47f6-ad38-f309b238d86d",
                    productName: "1년권",
                    defaultPrice: 363000,
                    dagymPrice: 326700,
                    dagymPriceRemainingCount: null,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스"],
                program: {
                    free: "",
                },
                service: {
                    free: "",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "61837da96bdf9700391007f7",
                gymName: "부평구청 타임짐휘트니스",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/17ce9a2dc2f2ea44fe/4K7xr2pEyhVMzEc5bz6PhzPHh3kDe3k4dKF3fvQKmHdh.jpg",
                address: "인천 부평구 부평동",
                location: [126.719892, 37.505882],
                review: {
                    rate: 5,
                    count: 3,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "ecfbc208-e939-49b0-9e62-761e4219d1fd",
                    productId: "e367ee19-1b4c-438e-aee6-dc4bd3cf620d",
                    productName: "헬스 이용권",
                    defaultPrice: 396000,
                    dagymPrice: 359000,
                    dagymPriceRemainingCount: 1,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "️가변주차가능 / ️샤워시설 / ️WI-FI / ️수건 / ️인바디 검사",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "637c6f2be38504001de06524",
                gymName: "부개 복싱인사이드짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1849e12404f415c4a3/2WQegG8qjHpnUFC6TgRQnt49mGB92r4erGS4.Big_다운로드.jpg",
                address: "인천 부평구 부개동",
                location: [126.737946802426, 37.49738364133078],
                review: {
                    rate: 5,
                    count: 1,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "934d1966-8b5d-4e04-8237-7e2442f29051",
                    productId: "b7a0abfa-c286-49a2-a1bd-20ee2f4a5690",
                    productName: "평일기간권(주5회)",
                    defaultPrice: 1500000,
                    dagymPrice: 1395000,
                    dagymPriceRemainingCount: 2,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["복싱"],
                program: {
                    free: "",
                },
                service: {
                    free: "",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "67a43fdc3354349be3637718",
                gymName: "청천 킹짐 6호점",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://dgmanager.s3.ap-northeast-2.amazonaws.com/gym-photo/50f31b79-9bbc-45bc-9709-5c8729aa18bb/1738557466108_a77c5720-d64f-4e6b-b833-ae1178e731ca.jpg",
                address: "인천 부평구 청천동",
                location: [126.71772724210626, 37.50636961372883],
                review: {
                    rate: 4.56,
                    count: 9,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "7502dbf0-2e24-4cd5-aaaa-d89256e9a57e",
                    productId: "f3435dab-2d72-4d95-b140-d6ccb07b4315",
                    productName: "헬스 이용권2",
                    defaultPrice: 328900,
                    dagymPrice: 328900,
                    dagymPriceRemainingCount: 0,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스"],
                program: {
                    free: "무료pt",
                },
                service: {
                    free: "무료주차",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: 1,
                isSportsFacilityCertified: true,
                isDagymRecommended: false,
            },
            {
                _id: "62a6c095123b8b001d5372bb",
                gymName: "부개 유알짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/1815b6048d82eaa98f/2YAY27HTZEX5jrM59yHhRxJjVP6RJZ5fpEMb.background_photo.jpg",
                address: "인천 부평구 부개동",
                location: [126.734291295753, 37.504187692879],
                review: {
                    rate: 5,
                    count: 7,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "59143dd2-68db-4401-afb1-e300be2240c8",
                    productId: "4be962d4-12d2-4e51-8153-88b8563c6b51",
                    productName: "2025 초특가 회원권",
                    defaultPrice: 440000,
                    dagymPrice: 418000,
                    dagymPriceRemainingCount: 3,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "P.T"],
                program: {
                    free: "",
                },
                service: {
                    free: "30회 PT 등록시! 회원복 & 락커 제공! / 수건 무료 제공 / 일일 입장제한 X / 등록시 무료 피티 1회 제공",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "607e39c0c70b9e0039942978",
                gymName: "일신 엘케이짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/178ed1197661950cf3/4K7pEJtywheyiTpxFR77dyrYXAUzUyZ2H6ZF7KydMs6f.jpg",
                address: "인천 부평구 일신동",
                location: [126.7423431015642, 37.48623588383842],
                review: {
                    rate: 5,
                    count: 3,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "46036f6a-7023-4d92-8f7a-0a8738d3509c",
                    productId: "2cd9eab0-5248-401f-b6d1-f117438640b5",
                    productName: "헬스+운동복",
                    defaultPrice: 363000,
                    dagymPrice: 329000,
                    dagymPriceRemainingCount: 2,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스", "P.T"],
                program: {
                    free: "O.T (상시지도)",
                },
                service: {
                    free: "수건 / 운동복 / 체성분 분석 / Wi-fi / 주차(18시 이후 무료주차)",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: false,
            },
            {
                _id: "6286411618d341001d0b01dc",
                gymName: "부개 바디패션짐 본점 24시",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/180dc6e41623842c1/NtZrSjU5q8XNDU3AEnkx1TXgn5xEzH18Hu.센터 Big 복사.jpg",
                address: "인천 부평구 부개동",
                location: [126.7396483329674, 37.50401428488515],
                review: {
                    rate: 4.23,
                    count: 13,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: false,
                isLiked: false,
                price: {
                    priceId: "14b72fa6-9330-4201-ab76-b78833ddc6c3",
                    productId: "d8f12223-6910-4eab-8e21-b92c926b4d1b",
                    productName: "헬스 회원권",
                    defaultPrice: 249000,
                    dagymPrice: 223000,
                    dagymPriceRemainingCount: 1,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스"],
                program: {
                    free: "️O.T 1회(선택사항)",
                },
                service: {
                    free: "",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: null,
                isSportsFacilityCertified: false,
                isDagymRecommended: true,
            },
            {
                _id: "59f61259b0993a41223b764d",
                gymName: "삼산 테크노짐",
                gymPhotoBig: null,
                gymPhotoSmall:
                    "https://stone-i-dagym-centers.s3.ap-northeast-2.amazonaws.com/images/gyms/15f6937ac63467f188/2YUaDbsiTfQiNNsQYP4q6vDbwgDj5V5HAjFv.센터 Big 복사.jpg",
                address: "인천 부평구 삼산동",
                location: [126.735858, 37.507097],
                review: {
                    rate: 5,
                    count: 37,
                },
                isWomenOnly: false,
                isReservationRequired: false,
                isLowestPrice: true,
                hasDailyItem: true,
                isLiked: false,
                price: {
                    priceId: "55106639-1ac0-4edb-8e58-25b8809438d5",
                    productId: "4783bd88-3d70-49ef-b20d-41c12bcfea96",
                    productName: "헬스 회원권",
                    defaultPrice: 506000,
                    dagymPrice: 501000,
                    dagymPriceRemainingCount: 2,
                    productCategory: "general",
                    productType: "period",
                    periodUnit: "month",
                    period: 12,
                    count: null,
                },
                exhibitionRemainingCount: null,
                tags: ["헬스"],
                program: {
                    free: "-G.X [파워덤벨 / 코어트레이닝 / 요가 / 댄스에어로빅 / 전신스트레칭 / S-라인체조] /  / O.T 1회 (*간단한 기구설명 및 동기부여)",
                },
                service: {
                    free: "주차 3시간 / 인바디 측정",
                },
                label: null,
                videoUrl: null,
                videoThumbnailUrl: null,
                coupons: null,
                culturalTaxDeductionRate: 1,
                isSportsFacilityCertified: true,
                isDagymRecommended: false,
            },
        ],
    },
};
